site_name: Graphic Server Protocol
site_description: "âš¡ GSP: A high-performance graphics server protocol for efficient rendering and visualization."
site_author: GSP Team
site_dir: mkdocs_build

docs_dir: mkdocs_source

theme:
  name: material # built-in theme

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - fenced_code

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_root_heading: true
            show_source: true
            show_signature_annotations: true
            annotations_path: full
            napoleon_google_docstring: true
            napoleon_numpy_docstring: true

# Social media links in the footer
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/vispy/GSP_API

# Github repository information
repo_url: https://github.com/vispy/GSP_API
repo_name: GSP_API

# Navigation structure
nav:
  - Home: index.md
  - About: about.md
  - API Reference:
      - GSP: api/gsp.md
      - GSP Network: api/gsp_network.md
      - GSP Pydantic: api/gsp_pydantic.md
      - GSP Matplotlib: api/gsp_matplotlib.md
      - GSP Datoviz: api/gsp_datoviz.md
      - GSP Extra: api/gsp_extra.md
      - Vispy 2: api/vispy_2.md
